[package]
name = "monotask-net"
version = "1.3.0"
edition = "2021"

[dependencies]
iroh             = "1.0"
monotask-core    = { path = "../monotask-core" }
monotask-crypto  = { path = "../monotask-crypto" }
monotask-storage = { path = "../monotask-storage" }
automerge   = { workspace = true }
sha2        = { workspace = true }
hex         = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
tokio       = { workspace = true }
serde       = { workspace = true }
ciborium    = { workspace = true }
rusqlite    = { workspace = true }

[dev-dependencies]
tempfile    = { workspace = true }
tokio       = { workspace = true }
